### ISSUE TITLE
Enhancement: Use WiFiManager for example connection sketch

### ISSUE THREAD

**Issue by LongLiveCHIEF** [ItayRosen/OpenIoT#2]
The current example connection sketch given requires you use hardcoded passwords for your network connection. If users use source control for their code, they'd potentially compromise their own home security by committing sensitive information.

I propose instead that we show an example connection sketch that use the `WiFiManager` library, which allows you to connect your device to a network, and saves that data to the device EEPROM, without putting any information about your network in your code.

You can then use the `WiFiManager` library to retrieve the required connection params and feed them to the `OpenIoT client()`.

See: [github.com/tzapu/WiFiManager](https://github.com/tzapu/WiFiManager))

**Comment by LongLiveCHIEF** [comment]
Looks like we could also use the [WiFiManager Custom Parameters](https://github.com/tzapu/WiFiManager#custom-parameters) to create params for the OpenIoT token and connection info, so that you wouldn't need to store those sensitive pieces of info in code either.

**Comment by ItayRosen** [comment]
Great idea. I will create a WiFiManager example sketch.

**Comment by ItayRosen** [comment]
I've added support through the library and added an example.
