### ISSUE TITLE
MQTT issue

### ISSUE THREAD

**Issue by pmajerus** [ItayRosen/OpenIoT#5]
device connects to local network does not connect to MQTT,  any advice for trouble shooting will be appreciated.

**Comment by ItayRosen** [comment]
Hi, show us your code. Also, what device are you using?

**Comment by pmajerus** [comment]
This is my device, ESP8266 NodeMCU LUA CP2102 ESP-12E.

I copied and pasted your code from the example in your introduction.

#include <Openiot.h>
//set your wifi credentials and OpenIoT token
const char *ssid = "my network";
const char *password = "my passwrd";
const char *token = "-Le-C9oxiETqBBodq0Vl/d799bea89f321a51c90d";  //this is
tokten hat you provided in the web app
//create a client
WiFiClient wifi;
Openiot client(wifi, ssid, password, token);
//create a variable that we can attach later
String myVariable = "Hello";
void setup() {
  //Set serial port for debugging
  Serial.begin(9600);
  client.setStream(Serial);

  //Start client
  client.begin();

  //Attach variable
  client.attachVariable(myVariable,"My Variable");
}
void loop() {
  //Run client on loop
  client.loop();
  //Print the variable every 5 seconds
  Serial.println(myVariable);
  delay(5000);
}

**Comment by ItayRosen** [comment]
Hi, try now. I think I've had an issue with the mosquitto service. Let me know the outcome.
