### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by pmajerus** [ItayRosen/OpenIoT#8]
email notifications not working again.

**Comment by ItayRosen** [comment]
Hi, I've just tried with both GPIO and Variables elements and the email notification worked fine. Can you show me your code?

**Comment by pmajerus** [comment]
I got the notification, maybe there is some latency.  Could you describe
the source of the timestamp?

**Comment by ItayRosen** [comment]
It should be nearly instant. What do you mean by source of timestamp?

**Comment by pmajerus** [comment]
what time zone are you in?

**Comment by ItayRosen** [comment]
UTC +3
