### ISSUE TITLE
temperature reading

### ISSUE THREAD

**Issue by pmajerus** [ItayRosen/OpenIoT#9]
Do you  plan to add a gadget like a dth11 or one wire for temperature readings?

**Comment by ItayRosen** [comment]
The Variable element is exactly for this. Here's an example code (using DHTLib library):
````
#include <dht.h>
#include <Openiot.h>

const char *token = "TOKEN";
const char *wifiName = "WIFI";
const char *password = "PASSWORD";

WiFiClient wifi;
Openiot client(wifi, wifiName, password, token);
dht DHT;

#define dht_apin A0 // Analog Pin sensor is connected to
int humidity = 0;
int temperature = 0;
  
void setup() {
  Serial.begin(9600);
  client.setStream(Serial);
  client.begin();
  //attach humidity and temperature variables
  client.attachVariable(humidity, "Humidity");
  client.attachVariable(temperature, "Temperature");
}
 
void loop(){
    //read sensor data and store it in variables
    DHT.read11(dht_apin);
    humidity = DHT.humidity;
    temperature = DHT.temperature;
    //run client and wait 5s until next read
    client.loop(); 
    delay(5000);
}
````

**Comment by pmajerus** [comment]
how do I generate the token?

**Comment by pmajerus** [comment]
Can I reuse an old token?

**Comment by ItayRosen** [comment]
You can re-use a token. Currently there is no option to generate a new one. If the token is compromised then you can create a new Thing.

**Comment by pmajerus** [comment]
Thanks

**Comment by pmajerus** [comment]
I am not sure where to put the code for the DHT11, I have it running on the
esp8266 but not sure how it fits into the openiot framework.

**Comment by ItayRosen** [comment]
Show me your code, I'll help you integrate.

**Comment by pmajerus** [comment]
#include "DHTesp.h"

#ifdef ESP32
#pragma message(THIS EXAMPLE IS FOR ESP8266 ONLY!)
#error Select ESP8266 board.
#endif

DHTesp dht;

void setup()
{
  Serial.begin(115200);
  Serial.println();
  Serial.println("Status\tHumidity (%)\tTemperature (C)\t(F)\tHeatIndex
(C)\t(F)");
  String thisBoard= ARDUINO_BOARD;
  Serial.println(thisBoard);

  // Autodetect is not working reliable, don't use the following line
  // dht.setup(17);
  // use this instead:
  dht.setup(05, DHTesp::DHT11); // Connect DHT sensor to GPIO D1
}

void loop()
{
  delay(3000);

  float humidity = dht.getHumidity();
  float temperature = dht.getTemperature();

  Serial.print(dht.getStatusString());
  Serial.print("\t");
  Serial.print(humidity, 1);
  Serial.print("\t\t");
  Serial.print(temperature, 1);
  Serial.print("\t\t");
  Serial.print(dht.toFahrenheit(temperature), 1);
  Serial.print("\t\t");
  Serial.print(dht.computeHeatIndex(temperature, humidity, false), 1);
  Serial.print("\t\t");
  Serial.println(dht.computeHeatIndex(dht.toFahrenheit(temperature),
humidity, true), 1);
}

**Comment by ItayRosen** [comment]
Here you go:
````
#include "DHTesp.h"
#include <Openiot.h>

//OpenIoT Credentials
const char *token = "TOKEN";
const char *wifiName = "WIFI";
const char *password = "PASSWORD";

#ifdef ESP32
#pragma message(THIS EXAMPLE IS FOR ESP8266 ONLY!)
#error Select ESP8266 board.
#endif

DHTesp dht;
Openiot client(wifi, wifiName, password, token);

float humidity = 0;
float temperature = 0;

void setup()
{
  Serial.begin(115200);
  Serial.println();
  Serial.println("Status\tHumidity (%)\tTemperature (C)\t(F)\tHeatIndex
(C)\t(F)");
  String thisBoard= ARDUINO_BOARD;
  Serial.println(thisBoard);
  
  //OpenIoT code
  client.setStream(Serial);
  client.begin();
  client.attachVariable(humidity, "Humidity");
  client.attachVariable(temperature, "Temperature");

  // Autodetect is not working reliable, don't use the following line
  // dht.setup(17);
  // use this instead:
  dht.setup(05, DHTesp::DHT11); // Connect DHT sensor to GPIO D1
}

void loop()
{
  delay(3000);

  humidity = dht.getHumidity();
  temperature = dht.getTemperature();

  Serial.print(dht.getStatusString());
  Serial.print("\t");
  Serial.print(humidity, 1);
  Serial.print("\t\t");
  Serial.print(temperature, 1);
  Serial.print("\t\t");
  Serial.print(dht.toFahrenheit(temperature), 1);
  Serial.print("\t\t");
  Serial.print(dht.computeHeatIndex(temperature, humidity, false), 1);
  Serial.print("\t\t");
  Serial.println(dht.computeHeatIndex(dht.toFahrenheit(temperature),
humidity, true), 1);

	client.loop(); 
}
````
